blank_issues_enabled: false
contact_links:
  - name: â“ Questions
    url: https://github.com/colinwilson/lotusdocs/discussions/new?category=q-a
    about: Please use the community forum for help and questions regarding Lotus Docs
  - name: ğŸ’¡ Feature requests and ideas
    url: https://github.com/colinwilson/lotusdocs/discussions/new?category=feature-requests
    about: Please vote for and post new feature ideas in the community forum
  - name: ğŸ“– Documentation
    url: https://lotusdocs.dev/docs/
    about: A great place to find instructions and answers on how to get the most out of your Lotus Docs themed site
